<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXcxxn5f\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXcxxn5f/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXcxxn5f.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXcxxn5f\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXcxxn5f\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xcxxn5f',
    'container.build_id' => '166f7f9a',
    'container.build_time' => 1546420148,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXcxxn5f');
